project:
  type: website
  output-dir: docs

website:
  title: "Cait Harrigan"
  favicon: "images/ch_logo.png"
  navbar:
    left:
      - text: 'Research'
        href: /#research
      - text: 'Talks'
        href: /#talks
      - text: 'Teaching'
        href: /#teaching
    right:
      - text: 'Blog'
        href: blog.qmd
      - text: 'CV'
        href: files/cv_2pg.pdf
  google-analytics: 'G-01XD03JCPM'
format:
  html:
    theme: 
      light: [flatly, css/theme-light.scss]
      dark: [flatly, css/theme-dark.scss]
    css: [css/custom.css,
          "https://use.fontawesome.com/releases/v6.0.0/css/all.css",
          "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"
          ]
    email-obfuscation: references
