project:
  type: website
  output-dir: docs

website:
  title: "Cait Harrigan"
  favicon: images/ch_logo.png
  navbar:
    right:
      - text: 'About'
        href: index.qmd
      - text: 'Research'
        href: https://www.caitharrigan.ca/#research
      - text: 'Talks'
        href: https://www.caitharrigan.ca/#talks
      - text: 'Teaching'
        href: https://www.caitharrigan.ca/#teaching
      - text: 'CV'
        href: cv.qmd
  google-analytics: 'G-01XD03JCPM'
format:
  html:
    theme: 
      light: [flatly, css/theme-light.scss]
      dark: [flatly, css/theme-dark.scss]
    css: [css/custom.css,
          "https://use.fontawesome.com/releases/v6.0.0/css/all.css",
          "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"
          ]
    email-obfuscation: references
    copyright: Cait Harrigan
